line-length = 88
target-version = "py310"
fix = true

[lint]
select = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # unused arguments in functions
    "SIM", # simplify code constructs
    "PIE", # unnecessary code
    "TCH", # type-checking imports
    "PTH", # use pathlib
    "RUF", # ruff-specific rules
]
ignore = [
    "E501",  # Line length (handled by formatter)
    "B008",  # Do not perform function calls in argument defaults
    "B904",  # Allow raising exceptions without `from`
    "ARG002", # Unused arguments in class methods (common in base classes)
]

[lint.per-file-ignores]
"tests/*" = ["ARG001", "F401"]  # Allow unused args/imports in tests
"setup.py" = ["E501", "B008"]  # Relax setup.py constraints
"__init__.py" = ["F401"]  # Allow unused imports in __init__.py

[lint.isort]
known-first-party = []
force-single-line = false
combine-as-imports = true
split-on-trailing-comma = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = false

[lint.pycodestyle]
max-doc-length = 100

[lint.flake8-bugbear]
extend-immutable-calls = ["typer.Argument", "typer.Option"]