
export const SYMBOLS: string[] = [
    '1000PEPEUSDT',
    '1INCHUSDT',
    'AAVEUSDT',
    'ADAUSDT',
    'AGIUSDT',
    'AGIXUSDT',
    'ALGOUSDT',
    'ALTUSDT',
    'ANKRUSDT',
    'APEUSDT',
    'APEXUSDT',
    'APTUSDT',
    'ARBUSDT',
    'ARKMUSDT',
    'ARPAUSDT',
    'ARUSDT',
    'ASTRUSDT',
    'ATOMUSDT',
    'AVAXUSDT',
    'AXSUSDT',
    'BADGERUSDT',
    'BALUSDT',
    'BANDUSDT',
    'BATUSDT',
    'BCHUSDT',
    'BEAMXUSDT',
    'BIGTIMEUSDT',
    'BITUSDT',
    'BLURUSDT',
    'BLZUSDT',
    'BNBUSDT',
    'BONKUSDT',
    'BSVUSDT',
    'BTCUSDT',
    'C98USDT',
    'CELOUSDT',
    'CFXUSDT',
    'CHZUSDT',
    'CKBUSDT',
    'COMPUSDT',
    'COREUSDT',
    'CROUSDT',
    'CRVUSDT',
    'CTSIUSDT',
    'CVXUSDT',
    'CYBERUSDT',
    'DARUSDT',
    'DOGEUSDT',
    'DOTUSDT',
    'DYDXUSDT',
    'EDUUSDT',
    'EGLDUSDT',
    'ENAUSDT',
    'ENJUSDT',
    'EOSUSDT',
    'ETCUSDT',
    'ETHUSDT',
    'ETHWUSDT',
    'FETUSDT',
    'FILUSDT',
    'FLOKIUSDT',
    'FLOWUSDT',
    'FTMUSDT',
    'FXSUSDT',
    'GALAUSDT',
    'GASUSDT',
    'GFTUSDT',
    'GMTUSDT',
    'GMXUSDT',
    'GRTUSDT',
    'HBARUSDT',
    'HFTUSDT',
    'HOOKUSDT',
    'HOTUSDT',
    'ICPUSDT',
    'ICXUSDT',
    'IDUSDT',
    'ILVUSDT',
    'IMXUSDT',
    'INJUSDT',
    'IOSTUSDT',
    'IOTAUSDT',
    'JASMYUSDT',
    'JUPUSDT',
    'KASUSDT',
    'KAVAUSDT',
    'KDAUSDT',
    'KLAYUSDT',
    'KNCUSDT',
    'KSMUSDT',
    'LDOUSDT',
    'LINKUSDT',
    'LITUSDT',
    'LPTUSDT',
    'LRCUSDT',
    'LTCUSDT',
    'LUNA2USDT',
    'MANAUSDT',
    'MANTAUSDT',
    'MASKUSDT',
    'MATICUSDT',
    'MEMEUSDT',
    'MINAUSDT',
    'MKRUSDT',
    'MNTUSDT',
    'MTLUSDT',
    'NEARUSDT',
    'NEOUSDT',
    'NFPUSDT',
    'NTRNUSDT',
    'OCEANUSDT',
    'OGNUSDT',
    'OMGUSDT',
    'ONDOUSDT',
    'ONEUSDT',
    'ONTUSDT',
    'OPUSDT',
    'ORDIUSDT',
    'PENDLEUSDT',
    'PEOPLEUSDT',
    'PERPUSDT',
    'PIXELUSDT',
    'PYTHUSDT',
    'QNTUSDT',
    'QTUMUSDT',
    'RDNTUSDT',
    'RENUSDT',
    'RLCUSDT',
    'RNDRUSDT',
    'RONUSDT',
    'RPLUSDT',
    'RSRUSDT',
    'RUNEUSDT',
    'RVNUSDT',
    'SANDUSDT',
    'SATSUSDT',
    'SEIUSDT',
    'SFPUSDT',
    'SHIB1000USDT',
    'SKLUSDT',
    'SNXUSDT',
    'SOLUSDT',
    'SSVUSDT',
    'STGUSDT',
    'STORJUSDT',
    'STRKUSDT',
    'STXUSDT',
    'SUIUSDT',
    'SUSHIUSDT',
    'SYNUSDT',
    'TUSDT',
    'TIAUSDT',
    'TLMUSDT',
    'TRBUSDT',
    'TRXUSDT',
    'UMAUSDT',
    'UNFIUSDT',
    'UNIUSDT',
    'USDCUSDT',
    'VETUSDT',
    'WAVESUSDT',
    'WIFUSDT',
    'WLDUSDT',
    'WOOUSDT',
    'XAIUSDT',
    'XEMUSDT',
    'XLMUSDT',
    'XMRUSDT',
    'XRPUSDT',
    'XTZUSDT',
    'XVGUSDT',
    'YFIUSDT',
    'YGGUSDT',
    'ZECUSDT',
    'ZENUSDT',
    'ZETAUSDT',
    'ZILUSDT',
    'ZRXUSDT'
];

export const TIME_INTERVALS: { value: string; label: string }[] = [
  { value: '1', label: '1 Minute' },
  { value: '5', label: '5 Minutes' },
  { value: '15', label: '15 Minutes' },
  { value: '60', label: '1 Hour' },
  { value: '240', label: '4 Hours' },
  { value: 'D', label: '1 Day' },
];

/**
 * Determines the next two higher timeframes from the TIME_INTERVALS list.
 * @param primaryInterval - The value of the selected primary interval (e.g., '60').
 * @returns An object containing the secondary and tertiary interval values, or null if not available.
 */
export const getHigherTimeframes = (primaryInterval: string): { secondary: string | null; tertiary: string | null } => {
    const currentIndex = TIME_INTERVALS.findIndex(i => i.value === primaryInterval);
    if (currentIndex === -1 || currentIndex >= TIME_INTERVALS.length - 1) {
        return { secondary: null, tertiary: null };
    }

    const secondary = TIME_INTERVALS[currentIndex + 1] ? TIME_INTERVALS[currentIndex + 1].value : null;
    const tertiary = TIME_INTERVALS[currentIndex + 2] ? TIME_INTERVALS[currentIndex + 2].value : null;

    return { secondary, tertiary };
};