# -----------------------------------------------------------------------------
# Main Configuration for Javabot
# -----------------------------------------------------------------------------
# This file uses the new hierarchical structure. 
# Settings here will override the defaults defined in the schema.
# Environment variables (e.g., from a .env file) will override settings in this file.
# -----------------------------------------------------------------------------

# Common settings that apply across the entire application
common:
  # Bybit API Credentials. It is STRONGLY recommended to use a .env file for these.
  # API_KEY: YOUR_API_KEY_HERE
  # API_SECRET: YOUR_API_SECRET_HERE

  # --- Execution Mode ---
  # TESTNET: false      # Set to true to use the Bybit testnet
  # DRY_RUN: true       # Set to false to execute real trades. Defaults to true for safety.

  # --- General Bot Settings ---
  LOOP_WAIT_TIME_SECONDS: 10 # Time to wait between main loops
  ORDER_RETRY_ATTEMPTS: 3
  ORDER_RETRY_DELAY_SECONDS: 2

# Default settings for technical indicators
indicators:
  ATR_PERIOD: 14
  TREND_EMA_PERIOD: 50
  EMA_SHORT_PERIOD: 9
  EMA_LONG_PERIOD: 21
  RSI_PERIOD: 14
  ADX_PERIOD: 14
  EHLERS_FISHER_PERIOD: 10

# Configuration for individual trading strategies
strategies:
  # Ehlers Supertrend Strategy
  ehlst:
    enabled: false
    symbol: 'BTCUSDT'
    timeframe: '5' # 5-minute candles
    leverage: 10
    risk_per_trade_pct: 1.5

  # Whale Strategy
  whale:
    enabled: true # Let's enable this one to demonstrate
    symbol: 'BTCUSDT'
    timeframe: '5'
    loop_delay_seconds: 15
    signal_score_threshold: 2.5

  # Market Maker Strategy (currently disabled)
  market_maker:
    enabled: false

  # Channel Exit Strategy (currently disabled)
  chanexit:
    enabled: false

  # wbglm Strategy (currently disabled)
  wbglm:
    enabled: false